spring:
  cloud:
    stream:
      bindings:
        input:
          destination: training.example
          contentType: application/json
          group: default
        output:
          destination:
        binders:
          rabbit:
            type: rabbit
            environment:
              spring:
                rabbitmq:
                  host: localhost
                  port: 5672
                  username: guest
                  password: guest


